[build-system]
#requires = ["setuptools>=44", "wheel", "setuptools_scm[toml]>=3.4.3"]
#build-backend = "setuptools.build_meta"

requires = ["flit_core == 3.*"]
build-backend = "flit_core.buildapi"

[tool.setuptools_scm]

[tool.flit.metadata]
module = "ksykaitai"
author = "abitrolly"
