# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: build-test-release

on:
  push:
  #release:
  #  types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        pip install build
        ./prepare.sh
        ./release.sh

    - uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: |
          dist/*.whl
          tests/*

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wheel
    - name: Test
      run: |
        ls -la
        pip install dist/*.whl
        pytest tests/

  publish:
    if: false
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wheel
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
